#!/bin/bash
pacman-key --init
pacman-key --populate archlinux
mount /dev/sda1 /mnt
pacstrap /mnt base linux-zen linux-zen-headers linux-firmware openssh amd-ucode intel-ucode vi nano sudo 
genfstab -U /mnt >> /mnt/etc/fstab
ln -sf /usr/share/zoneinfo/Aisa/Seoul /etc/localtime
hwclock --systohc
nano /etc/locale.gen
locale-gen
nano /etc/locale.conf
LANG=ko_KR.UTF-8
nano /etc/vconsole.conf
nano /etc/hostname
mkinitcpio -P
echo 이제 나머지 작업을 하세요
exit 0
