#!/bin/ash
setup-sshd
vi /etc/ssh/sshd_config
rc-service sshd restart
passwd root
mkdir /media/setup
cp -a /media/sda/* /media/setup
mkdir /lib/setup
cp -a /.modloop/* /lib/setup
/etc/init.d/modloop stop
umount /dev/sda
mv /media/setup/* /media/sda/
mv /lib/setup/* /.modloop/
setup-apkrepos
vi /etc/apk/repositories
apk update
apk add dosfstools e2fsprogs pacman arch-install-scripts aria2 parted sudo
chmod 777 /etc/sudoers
vi /etc/sudoers
chmod 440 /etc/sudoers
fdisk /dev/sda
parted /dev/sda
mkfs.vfat /dev/sda15
mkfs.ext4 /dev/sda1
mount /dev/sda1 /mnt
mkdir -p /mnt/boot/EFI
mount /dev/sda15 /mnt/boot/EFI
mkdir /mnt/tmp
cd /mnt/tmp
aria2c -x16 -s16 https://seoul.mirror.pkgbuild.com/iso/2023.03.01/archlinux-bootstrap-2023.03.01-x86_64.tar.gz
tar xf archlinux-bootstrap-2023.03.01-x86_64.tar.gz
vi root.x86_64/etc/pacman.d/mirrorlist
arch-chroot root.x86_64/
pacman-key --init
pacman-key --populate archlinux
mount /dev/sda1 /mnt
pacstrap /mnt base linux-zen linux-zen-headers linux-firmware openssh amd-ucode intel-ucode vi nano sudo 
genfstab -U /mnt >> /mnt/etc/fstab
ln -sf /usr/share/zoneinfo/Aisa/Seoul /etc/localtime
hwclock --systohc
nano /etc/locale.gen
locale-gen
nano /etc/locale.conf
LANG=ko_KR.UTF-8
nano /etc/vconsole.conf
nano /etc/hostname
mkinitcpio -P
echo 이제 남은 작업을 하세요
exit 0
