#!/bin/bash
pacman-key --init
pacman-key --populate archlinux
mount /dev/sda1 /mnt
mount /dev/sda15 /mnt/boot
pacstrap /mnt base linux-zen linux-zen-headers linux-firmware openssh amd-ucode intel-ucode vi nano sudo networkmanager ufw
genfstab -U /mnt >> /mnt/etc/fstab
#arch-chroot /mnt
echo 이제 나머지 작업을 하세요
exit 0
